server:
  port: 8085

spring:
  application:
    name: SESSION-SERVICE


  datasource:
    url: jdbc:postgresql://localhost:5432/codecollab_sessions
    username: <PASTE_YOUR_USERNAME>
    password: <PASTE_YOUR_PASSWORD>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka