server:
  port: 8086

spring:
  application:
    name: execution-service
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
