server:
  port: 8087

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/codecollab_users
    username: <PASTE_YOUR_USERNAME>
    password: <PASTE_YOUR_PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret-key: <PASTE_YOUR_JWT_SECRET_KEY_HERE>
      expiration: 86400000